/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mediateur;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author enpei
 */
public class inter extends javax.swing.JFrame {

    public Query Querry;
    public Employe empl = null;
    public Departement dep = null;

    /**
     * Creates new form inter
     */
    public inter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Employe = new javax.swing.JCheckBox();
        NomEmp = new javax.swing.JRadioButton();
        jComboBox1_NomEmp = new javax.swing.JComboBox<>();
        jTextField1_NomEmp = new javax.swing.JTextField();
        Salaire = new javax.swing.JRadioButton();
        jComboBox1_Salaire = new javax.swing.JComboBox<>();
        NumDeprt = new javax.swing.JRadioButton();
        jComboBox1_NumDeprt = new javax.swing.JComboBox<>();
        jTextField1_Salaire = new javax.swing.JTextField();
        jTextField1_NumDeprt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Département = new javax.swing.JCheckBox();
        NumDept = new javax.swing.JRadioButton();
        NomDept = new javax.swing.JRadioButton();
        Budget = new javax.swing.JRadioButton();
        jComboBox1_NumDept = new javax.swing.JComboBox<>();
        jComboBox2_NomDept = new javax.swing.JComboBox<>();
        jComboBox3_Budget = new javax.swing.JComboBox<>();
        jTextField1_NumDept = new javax.swing.JTextField();
        jTextField2_NomDept = new javax.swing.JTextField();
        jTextField3_Budget = new javax.swing.JTextField();
        Excute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Requete = new javax.swing.JTextArea();
        Result = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Resultat = new javax.swing.JTextArea();
        Reset = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        Order = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Employe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Employe.setText("Employé");
        Employe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeActionPerformed(evt);
            }
        });

        NomEmp.setText("NomEmp");
        NomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomEmpActionPerformed(evt);
            }
        });

        jComboBox1_NomEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=" }));
        jComboBox1_NomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_NomEmpActionPerformed(evt);
            }
        });

        Salaire.setText("Salaire");
        Salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaireActionPerformed(evt);
            }
        });

        jComboBox1_Salaire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "<=", ">=" }));

        NumDeprt.setText("NumDept");
        NumDeprt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumDeprtActionPerformed(evt);
            }
        });

        jComboBox1_NumDeprt
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<", ">=", "<=" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Employe)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NomEmp)
                                        .addComponent(Salaire)
                                        .addComponent(NumDeprt))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1_NomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1_Salaire, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1_NumDeprt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1_NomEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 48,
                                                Short.MAX_VALUE)
                                        .addComponent(jTextField1_Salaire)
                                        .addComponent(jTextField1_NumDeprt))
                                .addContainerGap(61, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NomEmp)
                                        .addComponent(jComboBox1_NomEmp, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1_NomEmp, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Employe)
                                        .addComponent(Salaire)
                                        .addComponent(jComboBox1_Salaire, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1_Salaire, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NumDeprt)
                                        .addComponent(jComboBox1_NumDeprt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1_NumDeprt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(45, Short.MAX_VALUE)));

        Employe.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        Département.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Département.setText("Département");
        Département.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DépartementActionPerformed(evt);
            }
        });

        NumDept.setText("NumDept");
        NumDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumDeptActionPerformed(evt);
            }
        });

        NomDept.setText("NomDept");
        NomDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomDeptActionPerformed(evt);
            }
        });

        Budget.setText("Budget");
        Budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BudgetActionPerformed(evt);
            }
        });

        jComboBox1_NumDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "<=", ">=" }));

        jComboBox2_NomDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=" }));

        jComboBox3_Budget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "<=", ">=" }));
        jComboBox3_Budget.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Département)
                                .addGap(54, 54, 54)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel3Layout.createSequentialGroup()
                                                        .addComponent(NumDept)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(jComboBox1_NumDept,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Budget)
                                                        .addComponent(NomDept))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jComboBox2_NomDept, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox3_Budget, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2_NomDept, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jTextField1_NumDept, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField3_Budget,
                                                javax.swing.GroupLayout.Alignment.TRAILING))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NumDept)
                                                        .addComponent(jComboBox1_NumDept,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1_NumDept,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Département)
                                                        .addComponent(NomDept)
                                                        .addComponent(jComboBox2_NomDept,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2_NomDept,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addComponent(Budget))
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jComboBox3_Budget, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField3_Budget,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        Excute.setBackground(new java.awt.Color(0, 255, 0));
        Excute.setText("Excute");
        Excute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    ExcuteActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Rêquete :");

        jTextArea_Requete.setColumns(20);
        jTextArea_Requete.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Requete);

        Result.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Result.setText("Resultat :");

        jTextArea_Resultat.setColumns(20);
        jTextArea_Resultat.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Resultat);

        Reset.setBackground(new java.awt.Color(255, 255, 0));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Quitter.setBackground(new java.awt.Color(255, 0, 0));
        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });

        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(Quitter, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Excute, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(29, 29, 29)))
                                .addGap(0, 5, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Result)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(142, 142, 142)
                                .addComponent(Order)
                                .addGap(106, 106, 106)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Result)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27,
                                                                Short.MAX_VALUE))
                                                .addGap(8, 8, 8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Order)
                                                .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172,
                                                        Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Excute)
                                                .addGap(18, 18, 18)
                                                .addComponent(Reset)
                                                .addGap(18, 18, 18)
                                                .addComponent(Quitter)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmployeActionPerformed
        // TODO add your handling code here:
        if (this.Employe.isSelected()) {
            empl = new Employe();

        } else {
            empl = null;

        }
    }// GEN-LAST:event_EmployeActionPerformed

    private void NomEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NomEmpActionPerformed
        // TODO add your handling code here:
        if (this.NomEmp.isSelected()) {
            empl.getNomEmp().setSelected(true);
            empl.getNomEmp().setName("NomEmp");
        } else {
            empl.getNomEmp().setSelected(false);
            empl.getNomEmp().setName("");
        }
    }// GEN-LAST:event_NomEmpActionPerformed

    private void SalaireActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SalaireActionPerformed
        // TODO add your handling code here:
        if (this.Salaire.isSelected()) {
            empl.getSalaire().setSelected(true);
            empl.getSalaire().setName("salaire");
        } else {
            empl.getSalaire().setSelected(false);
            empl.getSalaire().setName("");
        }
    }// GEN-LAST:event_SalaireActionPerformed

    private void NumDeprtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NumDeprtActionPerformed
        // TODO add your handling code here:
        if (this.NumDeprt.isSelected()) {
            empl.getNumDeprt().setSelected(true);
            empl.getNumDeprt().setName("Employe.NumDept");
        } else {
            empl.getNumDeprt().setSelected(false);
            empl.getNumDeprt().setName("");
        }
    }// GEN-LAST:event_NumDeprtActionPerformed

    private void jComboBox1_NomEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1_NomEmpActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1_NomEmpActionPerformed

    private void DépartementActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DépartementActionPerformed
        // TODO add your handling code here:
        if (this.Département.isSelected()) {
            dep = new Departement();

        } else {
            dep = null;

        }
    }// GEN-LAST:event_DépartementActionPerformed

    private void NumDeptActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NumDeptActionPerformed
        // TODO add your handling code here:
        if (Département.isSelected()) {
            dep.getNumDept().setSelected(true);
            dep.getNumDept().setName("département.NumDept");
        } else {
            dep.getNumDept().setSelected(false);
            dep.getNumDept().setName("");
        }

    }// GEN-LAST:event_NumDeptActionPerformed

    private void NomDeptActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NomDeptActionPerformed
        // TODO add your handling code here:
        if (Département.isSelected()) {
            dep.getNomDept().setSelected(true);
            dep.getNomDept().setName("NomDept");
        } else {
            dep.getNomDept().setSelected(false);
            dep.getNomDept().setName("");
        }

    }// GEN-LAST:event_NomDeptActionPerformed

    private void BudgetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BudgetActionPerformed
        // TODO add your handling code here:
        if (Département.isSelected()) {
            dep.getBudget().setSelected(true);
            dep.getBudget().setName("Budget");
        } else {
            dep.getBudget().setSelected(false);
            dep.getBudget().setName("");
        }

    }// GEN-LAST:event_BudgetActionPerformed

    private void ExcuteActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {// GEN-FIRST:event_ExcuteActionPerformed
        // TODO add your handling code here:

        // Querry = new Query(this.empl, this.dep,this);
        Querry = new Query(this.empl, this.dep, this);
        try {
            this.jTextArea_Requete.setText(Querry.prepare_Query());
            ResultSet rs = Querry.Excute_Query(Querry.prepare_Query());
            if (rs != null) {
                this.jTextArea_Resultat.setText(Querry.ExplorerResultat(rs));
            } else {
                this.jTextArea_Resultat.setText("Selectionner un Attribut !!!");
            }
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(inter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(inter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inter.class.getName()).log(Level.SEVERE, null, ex);
        }

    }// GEN-LAST:event_ExcuteActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        this.jTextArea_Requete.setText("");
        this.Employe.setSelected(false);
        this.Département.setSelected(false);
        this.NomEmp.setSelected(false);
        this.NumDeprt.setSelected(false);
        this.Salaire.setSelected(false);
        this.NumDept.setSelected(false);
        this.Budget.setSelected(false);
        this.NomDept.setSelected(false);
        this.Order.setSelected(false);
        this.jTextField1_Salaire.setText("");
        this.jTextField1_NomEmp.setText("");
        this.jTextField1_NumDeprt.setText("");
        this.jTextField1_NumDept.setText("");
        this.jTextField2_NomDept.setText("");
        this.jTextField3_Budget.setText("");
        this.jTextArea_Resultat.setText("");
        this.jComboBox1_NumDeprt.setSelectedIndex(0);
        this.jComboBox1_Salaire.setSelectedIndex(0);
        this.jComboBox1_NumDept.setSelectedIndex(0);
        this.jComboBox3_Budget.setSelectedIndex(0);
        this.empl = null;
        this.dep = null;
    }// GEN-LAST:event_ResetActionPerformed

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QuitterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }// GEN-LAST:event_QuitterActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_OrderActionPerformed

    public void setjTextArea_requet(String s) {
        this.jTextArea_Requete.setText(s);
    }

    public String getjTextField_Budget() {
        return jTextField3_Budget.getText();
    }

    public String getjTextField_NomDept() {
        return jTextField2_NomDept.getText();
    }

    public String getjTextField_NomEmp() {
        return jTextField1_NomEmp.getText();
    }

    public String getjTextField_Salaire() {
        return jTextField1_Salaire.getText();
    }

    public String getjText_NumDept() {
        return jTextField1_NumDept.getText();
    }

    public String getjText_NumDeprt() {
        return jTextField1_NumDeprt.getText();
    }

    // *-------------combobox
    public String jComboBox_Budget() {
        return jComboBox3_Budget.getSelectedItem().toString();
    }

    public String getjComboBox_NomDept() {
        return jComboBox2_NomDept.getSelectedItem().toString();
    }

    public String getjComboBox_NomEMp() {
        return jComboBox1_NomEmp.getSelectedItem().toString();
    }

    public String getjComboBox_Salaire() {
        return jComboBox1_Salaire.getSelectedItem().toString();
    }

    public String getjComboBox_Budget() {
        return jComboBox3_Budget.getSelectedItem().toString();
    }

    public String getjComboBox_NumDeprt() {
        return jComboBox1_NumDeprt.getSelectedItem().toString();
    }

    public String getjComoBox_NumDept() {
        return jComboBox1_NumDept.getSelectedItem().toString();
    }

    public boolean getOrder() {
        if (Order.isSelected()) {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Budget;
    private javax.swing.JCheckBox Département;
    private javax.swing.JCheckBox Employe;
    private javax.swing.JButton Excute;
    private javax.swing.JRadioButton NomDept;
    private javax.swing.JRadioButton NomEmp;
    private javax.swing.JRadioButton NumDeprt;
    private javax.swing.JRadioButton NumDept;
    private javax.swing.JCheckBox Order;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Result;
    private javax.swing.JRadioButton Salaire;
    private javax.swing.JComboBox<String> jComboBox1_NomEmp;
    private javax.swing.JComboBox<String> jComboBox1_NumDeprt;
    private javax.swing.JComboBox<String> jComboBox1_NumDept;
    private javax.swing.JComboBox<String> jComboBox1_Salaire;
    private javax.swing.JComboBox<String> jComboBox2_NomDept;
    private javax.swing.JComboBox<String> jComboBox3_Budget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_Requete;
    private javax.swing.JTextArea jTextArea_Resultat;
    private javax.swing.JTextField jTextField1_NomEmp;
    private javax.swing.JTextField jTextField1_NumDeprt;
    private javax.swing.JTextField jTextField1_NumDept;
    private javax.swing.JTextField jTextField1_Salaire;
    private javax.swing.JTextField jTextField2_NomDept;
    private javax.swing.JTextField jTextField3_Budget;
    // End of variables declaration//GEN-END:variables
}
